FROM ubuntu:18.04

LABEL maintainer="Herson Melo <hersonpc@gmail.com>"

WORKDIR /app

RUN \
    apt-get -y update && \
    apt-get -y install joe wget p7zip-full curl unzip build-essential zlib1g-dev libcurl4-gnutls-dev && \
    apt-get -y install mysecureshell && \
    apt-get -y autoremove && \
    apt-get -y autoclean

# RAD Studio Tokyo Release 3 (10.2.3)
RUN wget http://altd.embarcadero.com/releases/studio/19.0/PAServer/Release3/LinuxPAServer19.0.tar.gz

RUN \
    tar -xvf LinuxPAServer19.0.tar.gz && \
    rm LinuxPAServer19.0.tar.gz && \
    cd PAServer-19.0

WORKDIR /app/PAServer-19.0

CMD ["/app/PAServer-19.0/paserver", "-password="]

EXPOSE 64211
EXPOSE 8080